import type { CSSProperties } from "react";

/** Co-located styles for MultiAgentPicker (mirrors Dropdown/SearchableSelect's
   panel styling for a consistent look). */
export const s = {
  root: { position: "relative", display: "inline-block" } satisfies CSSProperties,
  panel: {
    position: "absolute",
    top: "calc(100% + 6px)",
    right: 0,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-strong)",
    borderRadius: 9,
    boxShadow: "var(--shadow-modal)",
    padding: 10,
    zIndex: 40,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  mergedWarning: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "4px 4px 0",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    maxHeight: 260,
    overflowY: "auto",
  } satisfies CSSProperties,
  row: { padding: "4px 4px" } satisfies CSSProperties,
  rowLabel: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    flex: 1,
    minWidth: 0,
  } satisfies CSSProperties,
  agentName: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  estimate: { fontSize: 12, color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  emptyRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "8px 4px",
    border: "none",
    background: "transparent",
    color: "var(--text-secondary)",
    fontSize: 13,
    textAlign: "left",
    cursor: "pointer",
  } satisfies CSSProperties,
  divider: { height: 1, background: "var(--border)" } satisfies CSSProperties,
  actionsRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  } satisfies CSSProperties,
  clearLink: {
    border: "none",
    background: "transparent",
    color: "var(--text-secondary)",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    padding: "4px 4px",
  } satisfies CSSProperties,
  footerLink: {
    border: "none",
    background: "transparent",
    color: "var(--text-muted)",
    fontSize: 12.5,
    textAlign: "left",
    cursor: "pointer",
    padding: "4px 4px 0",
  } satisfies CSSProperties,
} as const;
